twitter:
  auth:
    api-key: VQTDNetZ9OWKzjmqJyGMAg12E
    api-key-secret: cDkqSBfynr666ecIMovpZ8pNzXCFSqljeIYcQ7BazmIRdHg57E
    access-token: 1613212293457932291-puPQv88mKxZvt9zzzuxxbqljL1LfML
    access-token-secret: 6x9GRIrZGsjgtEnPq27XR1YC0bX4mytLv42EiX5ldMwsx
bot:
  tweetfreq:
    thirty-minutes: 1800000
    five-minutes: 300000
    hour: 3600000
    four-hours: 14400000
    day: 86400000
