twitter:
  auth:
    api-key: 
    api-key-secret: 
    access-token: 
    access-token-secret: 
bot:
  tweetfreq:
    thirty-minutes: 1800000
    five-minutes: 300000
    hour: 3600000
    four-hours: 14400000
    day: 86400000
